# Schema Registry listener address
listeners=http://0.0.0.0:8081

# Kafka cluster bootstrap servers
kafkastore.bootstrap.servers=PLAINTEXT://kafka:9092

# Topic used to store schemas
kafkastore.topic=_schemas

# Schema compatibility level
schema.compatibility.level=backward

debug=false
