#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

## Kyuubi Configurations

#
# kyuubi.authentication                    NONE
#
# kyuubi.frontend.bind.host                10.0.0.1
# kyuubi.frontend.protocols                THRIFT_BINARY,REST
# kyuubi.frontend.thrift.binary.bind.port  10009
# kyuubi.frontend.rest.bind.port           10099
#
# kyuubi.engine.type                       SPARK_SQL
# kyuubi.engine.share.level                USER
# kyuubi.session.engine.initialize.timeout PT3M
#
# kyuubi.ha.addresses                      zk1:2181,zk2:2181,zk3:2181
# kyuubi.ha.namespace                      kyuubi
#

# Details in https://kyuubi.readthedocs.io/en/master/configuration/settings.html

kyuubi.metadata.store.class org.apache.kyuubi.server.metadata.jdbc.JDBCMetadataStore
kyuubi.metadata.store.jdbc.database.type MYSQL
kyuubi.metadata.store.jdbc.url jdbc:mysql://mysql:3306/kyuubi?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
kyuubi.metadata.store.jdbc.user root
kyuubi.metadata.store.jdbc.password root
kyuubi.metadata.store.jdbc.driver com.mysql.cj.jdbc.Driver

kyuubi.engine.type                       SPARK_SQL
spark.master                             yarn
spark.sql.catalog.paimon_catalog_web         org.apache.paimon.spark.SparkCatalog
spark.sql.catalog.paimon_catalog_web.warehouse hdfs://hadoop:8020/warehouse/tablespace/external/hive/

flink.execution.target  yarn-application

kyuubi.engine.hive.deploy.mode  yarn
